<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Environmental Data Literacy</title>
  <meta name="description" content="A textbook for the use of R in environmental statistics.">
  <meta name="generator" content="bookdown 0.3.18 and GitBook 2.6.7">

  <meta property="og:title" content="Environmental Data Literacy" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A textbook for the use of R in environmental statistics." />
  <meta name="github-repo" content="dyerlab/applied_environmental_statisics" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Environmental Data Literacy" />
  
  <meta name="twitter:description" content="A textbook for the use of R in environmental statistics." />
  

<meta name="author" content="Rodney J. Dyer">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="spatial-data.html">
<link rel="next" href="summary-statistics.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="media/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Frontmatter</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#typography"><i class="fa fa-check"></i>Typography</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#interactive-content"><i class="fa fa-check"></i>Interactive Content</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#dedication"><i class="fa fa-check"></i>Dedication</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-literacy.html"><a href="data-literacy.html"><i class="fa fa-check"></i>Data Literacy</a></li>
<li class="part"><span><b>I Foundations</b></span></li>
<li class="chapter" data-level="1" data-path="the-r-ecosystem.html"><a href="the-r-ecosystem.html"><i class="fa fa-check"></i><b>1</b> The R Ecosystem</a><ul>
<li class="chapter" data-level="1.1" data-path="the-r-ecosystem.html"><a href="the-r-ecosystem.html#getting-r-configured"><i class="fa fa-check"></i><b>1.1</b> Getting R Configured</a><ul>
<li class="chapter" data-level="1.1.1" data-path="the-r-ecosystem.html"><a href="the-r-ecosystem.html#packages"><i class="fa fa-check"></i><b>1.1.1</b> Packages</a></li>
<li class="chapter" data-level="1.1.2" data-path="the-r-ecosystem.html"><a href="the-r-ecosystem.html#cran"><i class="fa fa-check"></i><b>1.1.2</b> CRAN</a></li>
<li class="chapter" data-level="1.1.3" data-path="the-r-ecosystem.html"><a href="the-r-ecosystem.html#github"><i class="fa fa-check"></i><b>1.1.3</b> GitHub</a></li>
<li class="chapter" data-level="1.1.4" data-path="the-r-ecosystem.html"><a href="the-r-ecosystem.html#bioconductor"><i class="fa fa-check"></i><b>1.1.4</b> Bioconductor</a></li>
<li class="chapter" data-level="1.1.5" data-path="the-r-ecosystem.html"><a href="the-r-ecosystem.html#troublesome-packages"><i class="fa fa-check"></i><b>1.1.5</b> Troublesome Packages</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="the-r-ecosystem.html"><a href="the-r-ecosystem.html#libraries-used"><i class="fa fa-check"></i><b>1.2</b> Libraries Used</a></li>
<li class="chapter" data-level="1.3" data-path="the-r-ecosystem.html"><a href="the-r-ecosystem.html#the-rstudio-environment"><i class="fa fa-check"></i><b>1.3</b> The RStudio Environment</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-types.html"><a href="data-types.html"><i class="fa fa-check"></i><b>2</b> Data Types</a><ul>
<li class="chapter" data-level="2.1" data-path="data-types.html"><a href="data-types.html#numeric-data-types"><i class="fa fa-check"></i><b>2.1</b> Numeric Data Types</a></li>
<li class="chapter" data-level="2.2" data-path="data-types.html"><a href="data-types.html#distributions"><i class="fa fa-check"></i><b>2.2</b> Distributions</a><ul>
<li class="chapter" data-level="2.2.1" data-path="data-types.html"><a href="data-types.html#coercion-to-numeric"><i class="fa fa-check"></i><b>2.2.1</b> Coercion to Numeric</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-types.html"><a href="data-types.html#characters"><i class="fa fa-check"></i><b>2.3</b> Characters</a><ul>
<li class="chapter" data-level="2.3.1" data-path="data-types.html"><a href="data-types.html#concatenation-of-characters"><i class="fa fa-check"></i><b>2.3.1</b> Concatenation of Characters</a></li>
<li class="chapter" data-level="2.3.2" data-path="data-types.html"><a href="data-types.html#coercion-to-characters"><i class="fa fa-check"></i><b>2.3.2</b> Coercion to Characters</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-types.html"><a href="data-types.html#factors"><i class="fa fa-check"></i><b>2.4</b> Factors</a><ul>
<li class="chapter" data-level="2.4.1" data-path="data-types.html"><a href="data-types.html#missing-levels-in-factors"><i class="fa fa-check"></i><b>2.4.1</b> Missing Levels in Factors</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="data-types.html"><a href="data-types.html#logical-types"><i class="fa fa-check"></i><b>2.5</b> Logical Types</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-containers.html"><a href="data-containers.html"><i class="fa fa-check"></i><b>3</b> Data Containers</a><ul>
<li class="chapter" data-level="3.1" data-path="data-containers.html"><a href="data-containers.html#vectors"><i class="fa fa-check"></i><b>3.1</b> Vectors</a></li>
<li class="chapter" data-level="3.2" data-path="data-containers.html"><a href="data-containers.html#matrices"><i class="fa fa-check"></i><b>3.2</b> Matrices</a></li>
<li class="chapter" data-level="3.3" data-path="data-containers.html"><a href="data-containers.html#lists"><i class="fa fa-check"></i><b>3.3</b> Lists</a></li>
<li class="chapter" data-level="3.4" data-path="data-containers.html"><a href="data-containers.html#data-frames"><i class="fa fa-check"></i><b>3.4</b> Data Frames</a><ul>
<li class="chapter" data-level="3.4.1" data-path="data-containers.html"><a href="data-containers.html#indexing-data-frames"><i class="fa fa-check"></i><b>3.4.1</b> Indexing Data Frames</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="manipulating-data.html"><a href="manipulating-data.html"><i class="fa fa-check"></i><b>4</b> Manipulating Data</a><ul>
<li class="chapter" data-level="4.1" data-path="manipulating-data.html"><a href="manipulating-data.html#data-import-export"><i class="fa fa-check"></i><b>4.1</b> Data Import &amp; Export</a></li>
<li class="chapter" data-level="4.2" data-path="manipulating-data.html"><a href="manipulating-data.html#diving-into-data"><i class="fa fa-check"></i><b>4.2</b> Diving Into Data</a></li>
<li class="chapter" data-level="4.3" data-path="manipulating-data.html"><a href="manipulating-data.html#factor-character-data"><i class="fa fa-check"></i><b>4.3</b> Factor &amp; Character Data</a></li>
<li class="chapter" data-level="4.4" data-path="manipulating-data.html"><a href="manipulating-data.html#indexing"><i class="fa fa-check"></i><b>4.4</b> Indexing</a></li>
<li class="chapter" data-level="4.5" data-path="manipulating-data.html"><a href="manipulating-data.html#sorting-ordering"><i class="fa fa-check"></i><b>4.5</b> Sorting &amp; Ordering</a></li>
<li class="chapter" data-level="4.6" data-path="manipulating-data.html"><a href="manipulating-data.html#manipulating-data-1"><i class="fa fa-check"></i><b>4.6</b> Manipulating Data</a></li>
<li class="chapter" data-level="4.7" data-path="manipulating-data.html"><a href="manipulating-data.html#tabulating"><i class="fa fa-check"></i><b>4.7</b> Tabulating</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="programming.html"><a href="programming.html"><i class="fa fa-check"></i><b>5</b> Programming</a><ul>
<li class="chapter" data-level="5.1" data-path="programming.html"><a href="programming.html#function-writing"><i class="fa fa-check"></i><b>5.1</b> Function Writing</a></li>
<li class="chapter" data-level="5.2" data-path="programming.html"><a href="programming.html#variable-scope"><i class="fa fa-check"></i><b>5.2</b> Variable Scope</a></li>
<li class="chapter" data-level="5.3" data-path="programming.html"><a href="programming.html#decision-making"><i class="fa fa-check"></i><b>5.3</b> Decision Making</a><ul>
<li class="chapter" data-level="5.3.1" data-path="programming.html"><a href="programming.html#the-if-pattern"><i class="fa fa-check"></i><b>5.3.1</b> The if Pattern</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="programming.html"><a href="programming.html#the-if-else-pattern"><i class="fa fa-check"></i><b>5.4</b> The <code>if-else</code> Pattern</a></li>
<li class="chapter" data-level="5.5" data-path="programming.html"><a href="programming.html#flow-control"><i class="fa fa-check"></i><b>5.5</b> Flow Control</a><ul>
<li class="chapter" data-level="5.5.1" data-path="programming.html"><a href="programming.html#the-for-loop"><i class="fa fa-check"></i><b>5.5.1</b> The <code>for()</code> Loop</a></li>
<li class="chapter" data-level="5.5.2" data-path="programming.html"><a href="programming.html#short-circuiting-the-loop"><i class="fa fa-check"></i><b>5.5.2</b> Short Circuiting the Loop</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="markdown.html"><a href="markdown.html"><i class="fa fa-check"></i><b>6</b> Markdown</a><ul>
<li class="chapter" data-level="6.1" data-path="markdown.html"><a href="markdown.html#markdown-1"><i class="fa fa-check"></i><b>6.1</b> Markdown</a></li>
<li class="chapter" data-level="6.2" data-path="markdown.html"><a href="markdown.html#marking-up-text"><i class="fa fa-check"></i><b>6.2</b> Marking up Text</a></li>
<li class="chapter" data-level="6.3" data-path="markdown.html"><a href="markdown.html#inserting-r-code-chunks"><i class="fa fa-check"></i><b>6.3</b> Inserting R Code Chunks</a><ul>
<li class="chapter" data-level="6.3.1" data-path="markdown.html"><a href="markdown.html#chunk-options"><i class="fa fa-check"></i><b>6.3.1</b> Chunk Options</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="markdown.html"><a href="markdown.html#variables-in-text"><i class="fa fa-check"></i><b>6.4</b> Variables in Text</a></li>
</ul></li>
<li class="part"><span><b>II Data</b></span></li>
<li class="chapter" data-level="7" data-path="manipulating-data-2.html"><a href="manipulating-data-2.html"><i class="fa fa-check"></i><b>7</b> Manipulating Data</a></li>
<li class="chapter" data-level="8" data-path="graphical-display.html"><a href="graphical-display.html"><i class="fa fa-check"></i><b>8</b> Graphical Display</a></li>
<li class="chapter" data-level="9" data-path="ggplot.html"><a href="ggplot.html"><i class="fa fa-check"></i><b>9</b> GGPlot</a></li>
<li class="chapter" data-level="10" data-path="spatial-data.html"><a href="spatial-data.html"><i class="fa fa-check"></i><b>10</b> Spatial Data</a></li>
<li class="part"><span><b>III Statistical Inferences</b></span></li>
<li class="chapter" data-level="11" data-path="statistical-inferences.html"><a href="statistical-inferences.html"><i class="fa fa-check"></i><b>11</b> Statistical Inferences</a><ul>
<li class="chapter" data-level="11.1" data-path="statistical-inferences.html"><a href="statistical-inferences.html#an-applied-example."><i class="fa fa-check"></i><b>11.1</b> An applied example.</a></li>
<li class="chapter" data-level="11.2" data-path="statistical-inferences.html"><a href="statistical-inferences.html#the-binomial"><i class="fa fa-check"></i><b>11.2</b> The Binomial</a></li>
<li class="chapter" data-level="11.3" data-path="statistical-inferences.html"><a href="statistical-inferences.html#a-frequentist-approach"><i class="fa fa-check"></i><b>11.3</b> A Frequentist Approach</a></li>
<li class="chapter" data-level="11.4" data-path="statistical-inferences.html"><a href="statistical-inferences.html#a-bayesian-approach"><i class="fa fa-check"></i><b>11.4</b> A Bayesian Approach</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="summary-statistics.html"><a href="summary-statistics.html"><i class="fa fa-check"></i><b>12</b> Summary Statistics</a><ul>
<li class="chapter" data-level="12.1" data-path="summary-statistics.html"><a href="summary-statistics.html#central-tendency"><i class="fa fa-check"></i><b>12.1</b> Central Tendency</a></li>
<li class="chapter" data-level="12.2" data-path="summary-statistics.html"><a href="summary-statistics.html#dispersion"><i class="fa fa-check"></i><b>12.2</b> Dispersion</a></li>
<li class="chapter" data-level="12.3" data-path="summary-statistics.html"><a href="summary-statistics.html#ordination"><i class="fa fa-check"></i><b>12.3</b> Ordination</a></li>
<li class="chapter" data-level="12.4" data-path="summary-statistics.html"><a href="summary-statistics.html#hierarchical-clustering"><i class="fa fa-check"></i><b>12.4</b> Hierarchical Clustering</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="correlation.html"><a href="correlation.html"><i class="fa fa-check"></i><b>13</b> Correlation</a><ul>
<li class="chapter" data-level="13.1" data-path="correlation.html"><a href="correlation.html#the-data"><i class="fa fa-check"></i><b>13.1</b> The Data</a></li>
<li class="chapter" data-level="13.2" data-path="correlation.html"><a href="correlation.html#parametric-correlations"><i class="fa fa-check"></i><b>13.2</b> Parametric Correlations</a></li>
<li class="chapter" data-level="13.3" data-path="correlation.html"><a href="correlation.html#non-parametric-correlation"><i class="fa fa-check"></i><b>13.3</b> Non-Parametric Correlation</a></li>
<li class="chapter" data-level="13.4" data-path="correlation.html"><a href="correlation.html#differences"><i class="fa fa-check"></i><b>13.4</b> Differences</a></li>
<li class="chapter" data-level="13.5" data-path="correlation.html"><a href="correlation.html#permutation"><i class="fa fa-check"></i><b>13.5</b> Permutation</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>14</b> Linear Regression</a><ul>
<li class="chapter" data-level="14.1" data-path="linear-regression.html"><a href="linear-regression.html#the-data-1"><i class="fa fa-check"></i><b>14.1</b> The Data</a></li>
<li class="chapter" data-level="14.2" data-path="linear-regression.html"><a href="linear-regression.html#least-squares-linear-regression"><i class="fa fa-check"></i><b>14.2</b> Least Squares Linear Regression</a></li>
<li class="chapter" data-level="14.3" data-path="linear-regression.html"><a href="linear-regression.html#fitting-a-linear-model"><i class="fa fa-check"></i><b>14.3</b> Fitting a Linear Model</a></li>
<li class="chapter" data-level="14.4" data-path="linear-regression.html"><a href="linear-regression.html#multiple-regression"><i class="fa fa-check"></i><b>14.4</b> Multiple Regression</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>15</b> Analysis of Variance</a><ul>
<li class="chapter" data-level="15.1" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#one-sample-hypotheses"><i class="fa fa-check"></i><b>15.1</b> One Sample Hypotheses</a><ul>
<li class="chapter" data-level="15.1.1" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#data-variability"><i class="fa fa-check"></i><b>15.1.1</b> Data Variability</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#two-sample-hypotheses"><i class="fa fa-check"></i><b>15.2</b> Two Sample Hypotheses</a></li>
<li class="chapter" data-level="15.3" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#many-sample-hypotheses"><i class="fa fa-check"></i><b>15.3</b> Many Sample Hypotheses</a><ul>
<li class="chapter" data-level="15.3.1" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#post-hoc-tests"><i class="fa fa-check"></i><b>15.3.1</b> Post-Hoc Tests</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="http://dyerlab.org" target="blank">the Dyer Laboratory</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Environmental Data Literacy</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistical-inferences" class="section level1">
<h1><span class="header-section-number">11</span> Statistical Inferences</h1>
<blockquote>
<p>All models are wrong, but some are useful. (George E.P. Box)</p>
</blockquote>
<p>So we have been able to take our data, visualize it, manipulate it, and now it is time to apply some model to the data so we can get some degree of confidence on the statements we are going to make.</p>
<div id="an-applied-example." class="section level2">
<h2><span class="header-section-number">11.1</span> An applied example.</h2>
<p>Consider the case where we are trying to determine the relative frequency of blue catfish (<em>Ictalurus furcatus</em>) in the James River.</p>
<div class="figure">
<img src="media/BlueCatfish_MattRath.jpg" alt="The blue catfish (Ictalurus furcatus), an invasive species in the James River watershed. Photo by Matt Rath (CC BY-NC 2.0)." />
<p class="caption">The blue catfish (<em>Ictalurus furcatus</em>), an invasive species in the James River watershed. Photo by Matt Rath (CC BY-NC 2.0).</p>
</div>
<p>This species is not native to this region, it is endemic to the midwest drainages in the US such as the Mississippi, Missouri, and Ohio rivers. In the 1970’s, individuals were introducted into both the James and Rappahannock rivers and in 1985 stock was released in the Mattaponi river which eventually populated the Pamunkey. In the interim, this species has had a tremendous impact on native fishes. Before we can come up with management plans and/or recommendations, we must establish some baseline census data on the frequency of this fish in the basin.</p>
<p>As a simple example, consider the case where you went out and caught 50 fish, 37 of which were blue cats.</p>
<p><img src="Environmental_Data_Literacy_files/figure-html/unnamed-chunk-165-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>From this, we can estimate the relative frequency of the invasive species as:</p>
<p><span class="math display">\[
p_{catfish} = \frac{N_{catfish}}{N_{catfish} + N_{other}} = \frac{37}{50} = 0.74
\]</span></p>
<p>So, empirically, we found <code>74%</code> of the captures were the invasive species and <code>26%</code> were other species.</p>
<p>Our underlying biological question here is one focusing on how common this invasive species is. In the data above, we had a single sample and found the relative frequency to be <span class="math inline">\(p=0.74\)</span>, though this just one sample. Is it really 74% ? How can we get any statistical confidence on this finding? Let’s take a short detour into how we develop statistical inferences using the binomial probability function as an example and then show how there are two different schools of thought on how to analyze these data</p>
</div>
<div id="the-binomial" class="section level2">
<h2><span class="header-section-number">11.2</span> The Binomial</h2>
<p>If you were to flip a coin, it is either <code>HEADS</code> or <code>TAILS</code>, and if it is a fair coin, then the frequency at which you find a <code>HEADS</code> can be determined by flipping it a large number of times and counting how many come up <code>HEADS</code>. Actually, this probability is drawn from a well-known distribution, the binomial distribution, which is constructed as follows.</p>
<p>Let the probability of getting <code>HEADS</code> be denoted as <span class="math inline">\(P(HEADS) = p\)</span> and the probability of not heads (or <code>TAILS</code> if you consider it to never land perfectly balanced on its side, and that would be silly), as <span class="math inline">\(1 - P(HEADS) = P(TAILS) = 1 - p = q\)</span>. Since either <code>HEADS</code> or <code>TAILS</code> must happen then <span class="math inline">\(p + q = 1\)</span>. Depending upon the number of times you flip the coin, you can come up with several different arrangements of <code>HEADS</code> (<code>H</code> for brevity) and <code>TAILS</code> (<code>T</code> similiarly).</p>
<p>Here are some scenarios:<br />
- <em>One flip:</em> <code>H</code> or <code>T</code>, both occuring at an expected rate of <span class="math inline">\(p\)</span> and <span class="math inline">\(q\)</span>.<br />
- <em>Two flips:</em> <code>HH</code> (rate is expected at <span class="math inline">\(p^2\)</span>) or <code>HT</code> (<span class="math inline">\(pq\)</span>) or <code>TH</code> (<span class="math inline">\(qp\)</span>) or <code>TT</code> (<span class="math inline">\(q^2\)</span>).<br />
- <em>Three flips:</em> <code>HHH</code> (which can be written as <span class="math inline">\(p^3q^0\)</span> since <span class="math inline">\(q^0=1\)</span>) or <code>HHT</code> (<span class="math inline">\(p^2q^1\)</span>) or <code>HTH</code> (<span class="math inline">\(pqp = p^2q^1\)</span>) or <code>THH</code> (<span class="math inline">\(q^1p^2\)</span>) or <code>HTT</code> (<span class="math inline">\(p^1q^2\)</span>) or <code>THT</code> (<span class="math inline">\(pq^2\)</span>) or <code>TTH</code> (<span class="math inline">\(pq^2\)</span>) or <code>TTT</code> (<span class="math inline">\(p^0q^3\)</span>).<br />
- etc.</p>
<p>As you can see, there are some patterns emerging for any set of <span class="math inline">\(N\)</span> coin flips.<br />
1. The probability of getting <span class="math inline">\(K\)</span> <code>H</code> is <span class="math inline">\(p^K\)</span> and getting <span class="math inline">\(N-K\)</span> <code>T</code> is <span class="math inline">\(q^{N-K}\)</span>. So if we are intersted in the simple question of 2 <code>H</code> and 1 <code>T</code> results, we have <span class="math inline">\(p^2q^1\)</span>.<br />
2. However, if you look at the iteration through the three flip case, there are many different ways you can get 2 <code>H</code> and 1 <code>T</code>. In fact, there are <span class="math inline">\(\frac{N!}{K!(N-K)!}\)</span> different ways.<a href="#fn3" class="footnoteRef" id="fnref3"><sup>3</sup></a></p>
<p>By doing this, we can define the binomial probability distribution as:</p>
<p><span class="math display">\[
P(K|N,p) = \frac{N!}{K!(N-K)!}p^K(1-p)^{N-k}
\]</span></p>
<p>In the coin example, we set (or assumed to set) <span class="math inline">\(p=q\)</span> but that does not necessarily have to be true. We could, for example, set <span class="math inline">\(p = 0.74\)</span> as in our fish example. It may be the case that the true frequency of blue catfish is <span class="math inline">\(p\)</span> as specified. However, it is also possible that you could take <span class="math inline">\(N\)</span> samples and get 0 catfish in the same way as it is possible to get <span class="math inline">\(N\)</span> <code>H</code> flips, right? Lets look at the distribution for a sampling haul that caught 10 fishes (or fish if on the extreme ends). First, set up some parameters,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p &lt;-<span class="st"> </span><span class="fl">0.74</span>
q &lt;-<span class="st"> </span><span class="dv">1</span>-p
N &lt;-<span class="st"> </span><span class="dv">10</span>
Catfish &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">0</span>,N)</code></pre></div>
<p>Then estimate the number of ways to get <span class="math inline">\(0\)</span>, <span class="math inline">\(1\)</span>, <span class="math inline">\(\ldots\)</span> <span class="math inline">\(N\)</span> catfish.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ways_to_get &lt;-<span class="st"> </span><span class="kw">choose</span>(N,Catfish)
ways_to_get</code></pre></div>
<pre><code>##  [1]   1  10  45 120 210 252 210 120  45  10   1</code></pre>
<p>This shows that while there is only one way to have all catfish (the first entry), there are 252 different ways to have 5 catfish! We have to attenuate these potential outcomes by the probability of observing <span class="math inline">\(0\)</span>, <span class="math inline">\(1\)</span>, <span class="math inline">\(\ldots\)</span> <span class="math inline">\(N\)</span> catfish given the frequency at which they occur in the river.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prob_of_each &lt;-<span class="st"> </span>p^Catfish *<span class="st"> </span>q^(N-Catfish)
prob_of_each</code></pre></div>
<pre><code>##  [1] 1.411671e-06 4.017833e-06 1.143537e-05 3.254682e-05 9.263326e-05
##  [6] 2.636485e-04 7.503843e-04 2.135709e-03 6.078556e-03 1.730051e-02
## [11] 4.923990e-02</code></pre>
<p>And then overall, we put these together to get the total probabilities.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">data &lt;-<span class="st"> </span><span class="kw">data.frame</span>( Catfish, <span class="dt">Frequency =</span> ways_to_get *<span class="st"> </span>prob_of_each )
<span class="kw">ggplot</span>( data, <span class="kw">aes</span>(Catfish,Frequency)) +<span class="st"> </span><span class="kw">geom_col</span>() +<span class="st"> </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span>Catfish)</code></pre></div>
<p><img src="Environmental_Data_Literacy_files/figure-html/unnamed-chunk-169-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>So while the true underlying fraction of catfish is 74%, it is possible to get <span class="math inline">\(0\)</span>, <span class="math inline">\(1\)</span>, <span class="math inline">\(\ldots\)</span> <span class="math inline">\(N\)</span> catfish in a sample. So how do we gain meaninful inferences? Here are two of the most common ways.</p>
</div>
<div id="a-frequentist-approach" class="section level2">
<h2><span class="header-section-number">11.3</span> A Frequentist Approach</h2>
<p>This is by-in-large the most common approach to extracting statistical inferences from some data. Lets assume that the <em>true</em> underlying frequency is actually <span class="math inline">\(p=0.74\)</span> in the James River. A frequentist, accepting the knowledge in the graph above, would consider that the way to get a good understanding of what the real likelihood of catfish in the James would require us to go sample a large number of times. After all, any one sampling session could be a varied number of catfish even if we are drawing from a fixed population. However, if we sampled many times, on average, we could get a good approximation of what the true underlying frequency really is.</p>
<p>For simplicity, lets say we go out and capture 50 fish from 10 different locations. The samples we collected had the following number of catfish.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df &lt;-<span class="st"> </span><span class="kw">data.frame</span>( <span class="dt">Site =</span> <span class="dv">1</span>:<span class="dv">10</span>, <span class="dt">Catfish=</span><span class="kw">c</span>(<span class="dv">37</span>,<span class="dv">32</span>,<span class="dv">35</span>,<span class="dv">39</span>,<span class="dv">31</span>,<span class="dv">38</span>,<span class="dv">38</span>,<span class="dv">35</span>,<span class="dv">41</span>,<span class="dv">38</span>) )
df</code></pre></div>
<pre><code>##    Site Catfish
## 1     1      37
## 2     2      32
## 3     3      35
## 4     4      39
## 5     5      31
## 6     6      38
## 7     7      38
## 8     8      35
## 9     9      41
## 10   10      38</code></pre>
<p>This results in an average frequency of <span class="math inline">\(\bar{p}=\)</span> 0.728. Pretty close to the target of 74%, right? Theoretically, if we went out and sampled more times the average would tend towards the true frequency—this is called the <em>Central Limit Theorem</em>. Understanding how repetitive sampling tends to reveal underlying parameters (such as a mean value) is the basis of the frequentist approach.</p>
<p>With these data, we could easily test the NULL hypothesis, <span class="math inline">\(H_O: p = 0.74\)</span>, using a univariate Student’s <span class="math inline">\(t-\)</span>test. This test was developed in 1908 by William Sealy Gosset, a chemist working for Guinness brewery in Dublin Ireland (‘Student’ was apparently his pen name). While we will come back to this specific test later and get into more details about its use, for our purposes, we can use it directly in R. Most simple statistical models in R are depicted as a function with the name of the test and the suffix <code>.test()</code> attached to it. From this function, a result is returned as an object that has our answer in it.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">t.test</span>(df$Catfish, <span class="dt">mu =</span> <span class="dv">37</span>)
model</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  df$Catfish
## t = -0.60541, df = 9, p-value = 0.5599
## alternative hypothesis: true mean is not equal to 37
## 95 percent confidence interval:
##  34.15804 38.64196
## sample estimates:
## mean of x 
##      36.4</code></pre>
<p>Here we see the average number of catfish sampled across all runs was 36.4 catfish. The <span class="math inline">\(t-\)</span>statistic, as we will see, has a very specific distribution and given that we have 9 degrees of freedom (more on what this means also later), the probability associated with these set of observations is <span class="math inline">\(P =\)</span> 0.559864. If we think of the distribution of all the times we could go out and sample 50 fish from the James River <strong>and</strong> the true underlying frequency was actually 74%, then the collection of samples we had would be roughly in the <span class="math inline">\(56^{th}\)</span> percentile—right in the middle. As such, I fail to reject the null hypothesis (<span class="math inline">\(H_O: p = 0.74\)</span>) for these data<a href="#fn4" class="footnoteRef" id="fnref4"><sup>4</sup></a>. It may actually be 74%.</p>
<p>However, consider the following code. Here we examine the sequence of potential values for the relative frequency, ranging from no catfish to only catfish. After all, I kinda just made up the 74% number because that was a random draw from the first sampling session. As each sampling session is independent and many found differing (though close) numbers of catfish, who is to say that 75% is actually the true value.</p>
<p>Lets look at how the data observed the first time can be examined across all potential values for the true mean. In the figure below, I perform the <span class="math inline">\(t-\)</span>test using our original data and the hypothesis that the true mean is 0, 1, 2, , and 50 catfish. For each, I record the probability associated with testing the null hypothesis.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">potential &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">50</span>)
other_p.vals &lt;-<span class="st"> </span><span class="kw">unlist</span>(<span class="kw">lapply</span>( potential,<span class="dt">FUN =</span> function(x) {<span class="kw">t.test</span>(df$Catfish, <span class="dt">mu=</span>x)$p.value}))
data &lt;-<span class="st"> </span><span class="kw">data.frame</span>( potential,other_p.vals)
data$Reject &lt;-<span class="st"> </span><span class="ot">TRUE</span>
data$Reject[ data$other_p.vals &gt;=<span class="st"> </span><span class="fl">0.05</span>] &lt;-<span class="st"> </span><span class="ot">FALSE</span>
data$Reject &lt;-<span class="st"> </span><span class="kw">factor</span>( data$Reject, <span class="dt">ordered=</span><span class="ot">TRUE</span>, <span class="dt">levels=</span><span class="kw">c</span>(<span class="ot">TRUE</span>,<span class="ot">FALSE</span>))
<span class="kw">ggplot</span>(data,<span class="kw">aes</span>(<span class="dt">x=</span>potential,<span class="dt">y=</span>other_p.vals)) +<span class="st"> </span>
<span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">slope=</span><span class="dv">0</span>,<span class="dt">intercept =</span> <span class="fl">0.05</span>, <span class="dt">color=</span><span class="st">&quot;red&quot;</span>) +<span class="st"> </span>
<span class="st">  </span><span class="kw">geom_line</span>() +<span class="st"> </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">shape=</span>Reject)) +<span class="st">  </span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;True Mean&quot;</span>) +<span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Probability&quot;</span>) +
<span class="st">  </span><span class="kw">scale_shape_discrete</span>(<span class="st">&quot;Reject Ho&quot;</span>)</code></pre></div>
<p><img src="Environmental_Data_Literacy_files/figure-html/unnamed-chunk-172-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>We see that 35, 36, 37, and 38, are all values could not be rejected using a <span class="math inline">\(t-\)</span>test. This means that the actual frequency of <span class="math inline">\(\frac{35}{50} = 0.7\)</span>, <span class="math inline">\(\frac{36}{50} = 0.72\)</span>, <span class="math inline">\(\frac{37}{50} = 0.74\)</span>, and <span class="math inline">\(\frac{38}{50} = 0.76\)</span> are all potential frequencies for which the observations we made could not be rejected! So how do we know?</p>
<p>One way to get a better idea is to go sample more. “Always increase your sample size,” says the advisor to the student. If we captured all the fish in the James River, we would know exactly their relative frequencies–just by counting. However, we cannot sample them all (though Dr. Garman would really like to have all the catfish out of the James River).</p>
<p>The main idea here is that if we were to sample enough, the <em>Central Limit Theorem</em> states that we would assymptotically arrive at the true value of the underlying.</p>
</div>
<div id="a-bayesian-approach" class="section level2">
<h2><span class="header-section-number">11.4</span> A Bayesian Approach</h2>
<p>Using probability to represent uncertainty in all parts of a statistical model. Adapting a Bayesian approach requires three things:</p>
<ol style="list-style-type: decimal">
<li>Data consisting of several observations.</li>
<li>A generative model underlying the creation of the data.</li>
<li>Priors probabilities,</li>
</ol>
<p>In essence, we want to start with some data and try to figure out what the parameters are given some specified model.</p>
<p>A/B Testing</p>
<p><span class="math display">\[
P(A|B) = \frac{P(B|A)P(B)}{P(A)P(B)}
\]</span></p>
<p>Simple example. For a set of <span class="math inline">\(N\)</span> observations, consider the case where we have <span class="math inline">\(k\)</span> observations of species <code>A</code> and <span class="math inline">\(N-k\)</span> observations of species <code>B</code>. As an environmental scientist, we are interested in the frequency of each of these species in our sampling location. For simplicity, lets call the frequency of species <code>A</code> <span class="math inline">\(p\)</span> and the frequency of species <code>B</code> in our samples as <span class="math inline">\(q = 1-p\)</span>.</p>
<p>A frequentist would start with a hypothesis, such as <span class="math inline">\(H_O:\)</span><em>The species are equally frequenct</em>. In this case, it would amo</p>
<p><span class="math display">\[
P(X|N,k,p) = \frac{N!}{(N-k)!k!}p^{N-k}(1-p)^k
\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">observed &lt;-<span class="st"> </span><span class="kw">rbinom</span>(<span class="dv">25</span>,<span class="dv">1</span>,<span class="fl">0.42</span>)
observed</code></pre></div>
<pre><code>##  [1] 0 1 0 0 1 0 1 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0</code></pre>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="3">
<li id="fn3"><p>The <span class="math inline">\(X!\)</span> notation is defined as: <span class="math inline">\(X! = X * (X-1) * (X-2) * (X-3) * \dots * 3 * 2 * 1\)</span>. This number gets big QUICK so be careful.<a href="statistical-inferences.html#fnref3">↩</a></p></li>
<li id="fn4"><p>Notice here that I did not say ‘accept’ the null, we <strong>never</strong> accept null hypotheses, only fail to reject them.<a href="statistical-inferences.html#fnref4">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="spatial-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="summary-statistics.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"],
"instapaper": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
